{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "geargo.fullname" . }}-postgres
  labels:
    {{- include "geargo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "geargo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
